name: cli-jobs-pipelines-autompg
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - run-job.sh
      - setup.sh
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Check out repo
      uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v1.4.4
      with:
        creds: >
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
          }

    - name: Setup
      run: bash setup.sh
      continue-on-error: true

    - name: Run job
      run: bash -x ../../run-job.sh pipeline.yml
      working-directory: jobs/pipeline
